name: currency_detector
description: A Flutter app to detect Bhutanese currency for visually impaired users.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.6.3
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/currency.png
